bundler_args: --without development
language: ruby
before_install: gem install bundler -v '<2'
rvm:
  - 2.3
  - 2.4
  - 2.5.0
  - 2.6.3
matrix:
  fast_finish: true
deploy:
  provider: rubygems
  api_key:
    secure: H5OPkiOcBFpI34nxIdGc/Rj6nNQKBUR0ccyKBubFroXcVDftpA+TVx8Vq+sjYaM1GuZI1F3OJPLHXmuyYsnJ3M3yltG2pYpJehULdpVU6yMu6eaQ8UAzA8wbmM1ANWEGQi1giulnxHw9M08qFzECpZvDFJWjtCg9lws64emqPLA=
  gem: faraday_middleware
  on:
    tags: true
    repo: lostisland/faraday_middleware
    rvm: 2.5.0
    gemfile: Gemfile
    condition: "$TRAVIS_RUBY_VERSION == 2.5.0"
